name: test
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: |
        echo "skip=true" >> $GITHUB_ENV
    - if: '!env.skip'
      run: |
        echo should have skipped
    - run: |
        echo "skip=" >> $GITHUB_ENV
    - if: '!env.skip'
      run: |
        echo should not have skipped
