name: Post Release
on:
  release:
    types: [published]
jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
    - name: Update Releases
      run: |
        head -c32 /dev/urandom > foo.md
        git add foo.md
        git commit -am "update release notes to ${GITHUB_REF#refs/tags/}"
        git push
      env:
        GIT_AUTHOR_NAME: ${{ github.event.sender.login }}
        GIT_AUTHOR_EMAIL: ${{ github.event.sender.login }}@users.noreply.github.com
