name: Post Release
on:
  release:
    types: [published]
  push:
jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
    - name: Update Releases
      run: |
        head -c32 /dev/urandom > foo.md
        git add foo.md
        git config --global user.email "casperdcl@noreply.github.com"
        git config --global user.name "wiki-bot"
        git commit -am "update release notes to ${GITHUB_REF#refs/tags/}"
        git push
